apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: itrixpro/app:0.0.0.1.RELEASE
        ports:
        - containerPort: 5000 
